# Generated by Django 5.1.2 on 2024-12-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiDeTemps', '0002_classecours_salleperiode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'managed': True, 'verbose_name': 'classe'},
        ),
        migrations.AlterModelOptions(
            name='classecours',
            options={'managed': True, 'verbose_name': 'classe_cours'},
        ),
        migrations.AlterModelOptions(
            name='classeperiodecours',
            options={'managed': True, 'verbose_name': 'classe_periode_cours'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'managed': True, 'verbose_name': 'cours'},
        ),
        migrations.AlterModelOptions(
            name='directeur',
            options={'managed': True, 'verbose_name': 'Directeur'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'managed': True, 'verbose_name': 'enseignant'},
        ),
        migrations.AlterModelOptions(
            name='enseignantmatiere',
            options={'managed': True, 'verbose_name': 'enseignant_matiere'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'managed': True, 'verbose_name': 'etablissement'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': True, 'verbose_name': 'grade'},
        ),
        migrations.AlterModelOptions(
            name='jour',
            options={'managed': True, 'verbose_name': 'jour'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'managed': True, 'verbose_name': 'matiere'},
        ),
        migrations.AlterModelOptions(
            name='periode',
            options={'managed': True, 'verbose_name': 'periode'},
        ),
        migrations.AlterModelOptions(
            name='salleenseignant',
            options={'managed': True, 'verbose_name': 'salle_enseignant'},
        ),
        migrations.AlterModelOptions(
            name='senceur',
            options={'managed': True, 'verbose_name': 'senceur'},
        ),
        migrations.AlterModelOptions(
            name='typecours',
            options={'managed': True, 'verbose_name': 'type_cours'},
        ),
    ]
