# Generated by Django 5.1.2 on 2024-12-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiDeTemps', '0003_alter_classe_options_alter_classecours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeperiodecours',
            name='id_cours',
            field=models.ForeignKey(db_column='id_Cours', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmploiDeTemps.cours'),
        ),
        migrations.AlterField(
            model_name='classeperiodecours',
            name='id_periode',
            field=models.ForeignKey(db_column='id_Periode', on_delete=django.db.models.deletion.DO_NOTHING, to='EmploiDeTemps.periode'),
        ),
        migrations.CreateModel(
            name='ClasseEnseignantCours',
            fields=[
                ('id_classe', models.OneToOneField(db_column='id_classe', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='EmploiDeTemps.classe')),
                ('id_cours', models.ForeignKey(db_column='id_cours', on_delete=django.db.models.deletion.DO_NOTHING, to='EmploiDeTemps.cours')),
                ('id_enseignant', models.ForeignKey(db_column='id_eseignant', on_delete=django.db.models.deletion.DO_NOTHING, to='EmploiDeTemps.enseignant')),
            ],
            options={
                'db_table': 'classe_enseignant_cours',
                'managed': True,
            },
        ),
    ]
