# Generated by Django 5.1.3 on 2024-12-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiDeTemps', '0004_alter_classeperiodecours_id_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeenseignantcours',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='classeperiodecours',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classeenseignantcours',
            name='id_classe',
            field=models.ForeignKey(db_column='id_classe', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.classe'),
        ),
        migrations.AlterField(
            model_name='classeenseignantcours',
            name='id_cours',
            field=models.ForeignKey(db_column='id_cours', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.cours'),
        ),
        migrations.AlterField(
            model_name='classeenseignantcours',
            name='id_enseignant',
            field=models.ForeignKey(db_column='id_eseignant', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.enseignant'),
        ),
        migrations.AlterField(
            model_name='classeperiodecours',
            name='id_classe',
            field=models.ForeignKey(db_column='id_Classe', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.classe'),
        ),
        migrations.AlterField(
            model_name='classeperiodecours',
            name='id_cours',
            field=models.ForeignKey(db_column='id_Cours', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.cours'),
        ),
        migrations.AlterField(
            model_name='classeperiodecours',
            name='id_periode',
            field=models.ForeignKey(db_column='id_Periode', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmploiDeTemps.periode'),
        ),
    ]
