# Generated by Django 5.1.3 on 2024-12-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiDeTemps', '0007_alter_classeenseignantcours_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classeenseignantcours',
            unique_together={('id_enseignant', 'id_classe', 'id_cours')},
        ),
    ]
