# Generated by Django 5.1.3 on 2024-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiDeTemps', '0009_alter_classeenseignantcours_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
