# Generated by Django 5.1.2 on 2024-12-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "EmploiDeTemps",
            "0011_alter_classe_id_alter_cours_id_alter_directeur_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classeperiodecours",
            unique_together={("id_classe", "id_periode", "id_cours")},
        ),
        migrations.AlterUniqueTogether(
            name="salleperiode",
            unique_together={("id_periode", "id_salle")},
        ),
    ]
